stages:
  - base
  - test
  - build

prepare-base-docker:
  stage: base
  image: docker:stable
  when: manual
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -f Dockerfile.base -t registry.gitlab.com/tokenmill/crawling-framework/base:latest .
    - docker push registry.gitlab.com/tokenmill/crawling-framework/base:latest
    - docker rmi registry.gitlab.com/tokenmill/crawling-framework/base:latest

prepare-base-elasticsearch:
  stage: base
  image: docker:stable
  when: manual
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -f Dockerfile.es -t registry.gitlab.com/tokenmill/crawling-framework/elasticsearch:latest .
    - docker push registry.gitlab.com/tokenmill/crawling-framework/elasticsearch:latest
    - docker rmi registry.gitlab.com/tokenmill/crawling-framework/elasticsearch:latest

prepare-administration-ui:
  stage: base
  image: docker:stable
  when: manual
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -f Dockerfile.ui -t registry.gitlab.com/tokenmill/crawling-framework/ui:latest .
    - docker push registry.gitlab.com/tokenmill/crawling-framework/ui:latest
    - docker rmi registry.gitlab.com/tokenmill/crawling-framework/ui:latest

prepare-crawler:
  stage: base
  image: docker:stable
  when: manual
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -f Dockerfile.crawler -t registry.gitlab.com/tokenmill/crawling-framework/crawler:latest .
    - docker push registry.gitlab.com/tokenmill/crawling-framework/crawler:latest
    - docker rmi registry.gitlab.com/tokenmill/crawling-framework/crawler:latest

unit-tests:
  stage: test
  image: registry.gitlab.com/tokenmill/crawling-framework/base:latest
  when: always
  script:
    - mvn clean test

integration-tests:
  stage: test
  image: registry.gitlab.com/tokenmill/crawling-framework/base:latest
  services:
    - name: registry.gitlab.com/tokenmill/crawling-framework/elasticsearch:latest
      alias: elasticsearch
  when: always
  script:
    - mvn -Dtest=*TestInt -DfailIfNoTests=false clean test
