stages:
  - base
  - test
  - build

prepare-base-docker:
  stage: base
  image: docker:stable
  when: manual
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -f Dockerfile.base -t registry.gitlab.com/tokenmill/crawling-framework/base:latest .
    - docker push registry.gitlab.com/tokenmill/crawling-framework/base:latest
    - docker rmi registry.gitlab.com/tokenmill/crawling-framework/base:latest

unit-tests:
  image: registry.gitlab.com/tokenmill/crawling-framework/base:latest
  stage: test
  when: always
  script:
    - mvn clean test
