version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    ports: ["9200:9200"]
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    ports: ["5601:5601"]
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200