version: '2'

services:
  elasticsearch:
    image: registry.gitlab.com/tokenmill/crawling-framework/elasticsearch:latest
    ports: ["9200:9200"]
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    ports: ["5601:5601"]
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
  administration-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports: ["8081:8081"]
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
